project:
  type: website
  output-dir: docs

website:
  title: "OA Datenpraxis"
  navbar:
    left:
      - href: index.qmd
        text: Über das Projekt
      - partners.qmd
      - publications.qmd
      - news.qmd
      - impressum.qmd
    logo: logo_HU.png
    tools:
      - icon: envelope
        text: Mail
        href: mailto:info@mail.xyz
      - icon: mastodon
        text: Mastodon
        href: https://fediscience.org/@dorothearrr
  search: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

